name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta todos los días a medianoche UTC

  workflow_dispatch: # Permite ejecutarlo manualmente desde "Actions"

permissions:
  contents: write # Permite que el bot escriba en el repo

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Generar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit y push de la imagen generada
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output/
          git commit -m "Actualización automática del snake"
          git push
